meta_product_name: "Sponty app"
meta_title: "Sponty - whats next"
meta_description: "Be spontaneous but stay organized!"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
